apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopeso
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversaopeso
  template:
    metadata:
      labels:
        app: conversaopeso
    spec:
      containers:
      - name: conversaopeso
        image: rbiasibetti/conversao-peso:v1
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conversaopeso-service
spec:
  selector:
    app: conversaopeso
  ports:
    - port: 8083
    targetPort: 80
  type: LoadBalancer
